baseURL = "https://scalaxy.org/"
languageCode = "en-us"
title = "Scalaxy"
theme = "scalaxy"
enableRobotsTXT = true
disableKinds = ["taxonomy", "term"]

[params]
  description = "Scalaxy is a multi-purpose, cloud-ready distributed database written in Common Lisp."
  version = "1.6.7"
  repo = "https://github.com/scalaxy/scalaxy"
  domain = "scalaxy.org"

[menu]
  [[menu.main]]
    name = "Docs"
    url = "/docs/"
    weight = 10
  [[menu.main]]
    name = "Use Cases"
    url = "/use-cases/"
    weight = 20
  [[menu.main]]
    name = "Topologies"
    url = "/topologies/"
    weight = 30

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    style = "github"
    codeFences = true
    lineNos = false
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
